### ISSUE TITLE
[liste] Appeler la route de recherche

### ISSUE THREAD

**Issue by jcognet** [jcognet/airtable_sf#519]
* [ ] Si l'écran est filtrable, gérer la rechercher
* [ ] Ajouter l'appel AJAX #473
* [ ] Au lancement de l'appel, afficher le loader #518
* [ ] Afficher le résultat / erreur
* [ ] Cacher le loader #518 
* [ ] Mettre à jour le tri : il garde dans l'URL le paramètre de recherche
